---
title: "conditional_loops_task"
author: "Kimmy Wong"
format: html
---

## task 1
```{r}
pm2_5 <- 160

if(pm2_5 < 100) {
  print("Low to moderate risk")
} else if(pm2_5 >= 100 & pm2_5 < 150) {
  print("Unhealthy for sensitive groups")
} else if(pm2_5 >= 150)
  print("Health risk present")
  
```

## task 2
```{r}
library(stringr)
species <- "blue whale"

if(str_detect(species, "whale")) {
  print("You found a whale!")
}

```

## task 3
```{r}
base_burrito <- 6.50
main_ingredient <- c("steak")

if(str_detect(main_ingredient, "veggie")) {
  print(base_burrito) 
} else if(str_detect(main_ingredient, "chicken")) {
  print(base_burrito + 3)
} else if(str_detect(main_ingredient, "steak"))
  print(base_burrito + 3.25)

```

## task 4
```{r}
fish <- c(8, 10, 12, 13)

fish_prop <- vector(mode = "numeric", length = length(fish))

for(i in seq_along(fish)) {
  new_value <- fish[i]/sum(fish)
  fish_prop[i] <- new_value
}
```

## task 5
```{r}
for(i in seq_along(month.name)) {
  print(paste0(month.name[i], " is month", " ", i,"."))
}
```